DTSPO-75: added validation checks and variable
hmcts/terraform-module-frontdoor pull request #4
Opened 2020-11-10 08:05 UTC by mokainos

https://tools.hmcts.net/jira/browse/DTSPO-75

### Change description ###

1) Added Validation step and plan
2)  Added kv resource group variable  

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2020-11-10 08:13 UTC, dawsonrs approved these changes

2020-11-10 08:27 UTC, timja requested changes
remove the commented out code and fix the typoes please,

would be good if we can verify what happens if we remove the location variable

2020-11-10 08:27 UTC, timja commented on frontdoor.tf
> +  #location                                     = "global"
hmm will this break existing deployed ones? probably not but you shouldn't leave commented out code

```suggestion
```

2020-11-10 08:27 UTC, timja commented on main.tf
> +/**
is this file required?

2020-11-10 08:27 UTC, timja commented on validation/fd.tf
> +  source = "git::https://github.com/hmcts/terraform-module-frontdoor.git?ref=features/dtspo75_1"
make sure to update after merge

2020-11-10 08:27 UTC, timja commented on validation/provider.tf
> +  #skip_provider_registration = "true"
```suggestion
```

2020-11-10 08:27 UTC, timja commented on validation/provider.tf
> +  #version         = "= 2.4.0"
either choose a version or lock it
```suggestion
```

both have ±'s

2020-11-10 08:27 UTC, timja commented on variables.tf
> +  description = "Enter name of the subsription to deploy frontdoor"
```suggestion
  description = "Name of the subscription to deploy frontdoor, e.g. stg"
```

2020-11-10 08:27 UTC, timja commented on variables.tf
> +  description = "Enter name of the enviornment to deploy frontdoor"
```suggestion
  description = "Enter name of the environment to deploy frontdoor"
```

2020-11-10 08:27 UTC, timja commented on variables.tf
> +  description = "Enter Name of the project"
```suggestion
  description = "Name of the project"
```

2020-11-10 08:27 UTC, timja commented on variables.tf
> +  description = "Enter Azure location to deploy the resource"
```suggestion
  description = "Azure location to deploy the resource"
```

2020-11-10 08:27 UTC, timja commented on variables.tf
> +variable "location" {
We need to see if we actually need this now

2020-11-10 08:27 UTC, timja commented on variables.tf
> +  description = "Certificate source to encrypted HTTPS traffic with"
please specify the allowed values, AzureKeyVault is one I believe and Managed might be the other but look it up
```suggestion
  description = "Certificate source to encrypt HTTPS traffic with"
```

2020-11-10 08:27 UTC, timja commented on variables.tf
> +  description = "Name of the Monitoring enviornment"
```suggestion
  description = "Name of the log analytics workspace"
```

2020-11-10 08:27 UTC, timja commented on variables.tf
> +  description = "Enforce_backend_pools_certificate_name_check"
```suggestion
  description = "Enforce backend pools certificate name check"
```

2020-11-10 08:27 UTC, timja commented on variables.tf
> +variable "kv_resource_group" {
we haven't really abbreviated any other variables, this reads better
```suggestion
variable "key_vault_resource_group" {
```

2020-11-10 08:27 UTC, timja commented on variables.tf
> +  description = "Keyvault resource group name"
key vault has spaces in it's name https://azure.microsoft.com/en-gb/services/key-vault/
```suggestion
  description = "Key Vault resource group name"
```

2020-11-10 09:40 UTC, mokainos commented on frontdoor.tf
> +  #location                                     = "global"
Location argument is deprecated and defaults to "global" now

2020-11-10 10:03 UTC, timja commented on frontdoor.tf
> +  #location                                     = "global"
so remove then assuming the existing frontdoors work

2020-11-10 11:03 UTC, mokainos commented on frontdoor.tf
> +  #location                                     = "global"
removed it

2020-11-10 23:35 UTC, naikajah commented
Guys!! there are hell lot of issues with Terraform for Azure Frontdoor and it seems, its not going to get fixed anytime soon because of the way frontdoor APIs are designed. I suggest we also look into ARM templates for frontdoor specifically for Frontdoor. As ARM templates are much better to work with in case of frontdoor.

2020-11-11 10:13 UTC, mokainos commented on main.tf
> +/**
yes to add text to  README.md using terraform-docs

2020-11-11 10:13 UTC, mokainos commented on validation/fd.tf
> +  source = "git::https://github.com/hmcts/terraform-module-frontdoor.git?ref=features/dtspo75_1"
will do

2020-11-11 10:16 UTC, mokainos commented on validation/provider.tf
> +  #version         = "= 2.4.0"
Deleted them.

2020-11-11 10:16 UTC, mokainos commented on validation/provider.tf
> +  #skip_provider_registration = "true"
Deleted them.

2020-11-11 11:11 UTC, timja commented on README.md
> +| kv\_resource\_group | Keyvault resource group name | `string` | n/a | yes |
looks like the readme needs regenerating, this is the old var name

2020-11-11 12:31 UTC, mokainos commented on variables.tf
> +variable "location" {
Removed default entry

2020-11-11 12:46 UTC, mokainos commented on README.md
> +| kv\_resource\_group | Keyvault resource group name | `string` | n/a | yes |
updated README.md

2020-11-11 12:55 UTC, timja approved these changes

2020-11-11 13:16 UTC, merged