dtspo75: Migrate module across
hmcts/terraform-module-frontdoor pull request #5
Opened 2020-11-11 14:45 UTC by mokainos

https://tools.hmcts.net/jira/browse/DTSPO-75

Changed variable name
**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2020-11-11 15:07 UTC, timja requested changes

2020-11-11 15:07 UTC, timja commented on validation/sample.tfvars_old
> +key_vault_resource_group = "core-infra-sbox-rg"
what is this file it has an _old suffix?

2020-11-11 15:12 UTC, mokainos commented on validation/sample.tfvars_old
> +key_vault_resource_group = "core-infra-sbox-rg"
I was planning to use it. Currently i am not..

2020-11-11 15:46 UTC, timja commented on validation/sample.tfvars_old
> +key_vault_resource_group = "core-infra-sbox-rg"
please remove if you aren't using it

2020-11-12 09:22 UTC, timja approved these changes

2020-11-12 17:08 UTC, luigibk approved these changes

2020-11-13 09:04 UTC, merged